#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

leftwm-command "UnloadTheme"

pkill picom
pkill polybar
pkill dunst
pkill feh

if [ - "${SCRIPTPATH}/../config.ron.bak"]; then
  rm $SCRIPTPATH/../config.ron
  mv $SCRIPTPATH/../config.ron.bak $SCRIPTPATH/../config.ron
fi