#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# verifica si hay un tema cargado y es dado de baja
if [ -f "/tmp/leftwm-theme-down"]; then
  /tmp/leftwm-theme-down
  rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#configure keyboard layouts
setxkbmap "us,es" ",winkeys" "grp:rctrl_switch"

if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
fi

if [ -x "$(command -v feh)" ]; then
  feh --bg-fill --randomize $SCRIPTPATH/wallpapers/
fi

if [ -x "$(command -v dunst)" ]; then
  dunst -config $SCRIPTPATH/dunst/configrc.ini &
fi

mv ~/.config/leftwm/config.ron ~/.config/leftwm/config.ron.bak
cp $SCRIPTPATH/leftwm-config/config.ron ~/.config/leftwm/config.ron

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

polybar -m | sed s/:.*// | tac | while read -r monitor
do
  monitor=$monitor polybar -c ./polybar/config.ini main &> /tmp/polybar.log &
done
