#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
 echo $SCRIPTPATH
# verifica si hay un tema cargado y es dado de baja
if [ -f "/tmp/leftwm-theme-down" ]; then
  /tmp/leftwm-theme-down
  rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#configure keyboard layouts
setxkbmap "us,es" ",winkeys" "grp:rctrl_switch"

if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
fi

if [ -x "$(command -v feh)" ]; then
  feh --bg-fill --randomize $SCRIPTPATH/wallpapers/
fi

if [ -x "$(command -v dunst)" ]; then
  dunst -config $SCRIPTPATH/dunst/configrc.ini &
fi

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

for m in $(polybar --list-monitors | cut -d":" -f1); do
    monitor=$m polybar -c ./polybar/config.ini main &> /tmp/polybar.log &
done